apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-native-app-monitor
  namespace: default
  labels:
    app: cloud-native-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cloud-native-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
  namespaceSelector:
    matchNames:
    - default
