server:
  port: 8080

spring:
  application:
    name: cloud-native-app
  # Redis 配置（用于分布式限流）
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# Actuator 配置 - 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}

# 应用配置
app:
  rate-limit:
    # 是否启用分布式限流（需要 Redis）
    distributed: false

# 日志配置
logging:
  level:
    com.example.demo: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
